/**
 * Export images dictionary
 */

module.exports = [
  { "image": "500px", "translation": "500px" },
  { "image": "address-book", "translation": "libreta de direcciones" },
  { "image": "address-book-o", "translation": "libreta de direcciones-o" },
  { "image": "address-card", "translation": "tarjeta de dirección" },
  { "image": "address-card-o", "translation": "tarjeta de dirección-o" },
  { "image": "adjust", "translation": "ajustar" },
  { "image": "adn", "translation": "adn" },
  { "image": "align-center", "translation": "alinear al centro" },
  { "image": "align-justify", "translation": "justificar" },
  { "image": "align-left", "translation": "alinear a la izquierda" },
  { "image": "align-right", "translation": "alinear a la derecha" },
  { "image": "amazon", "translation": "amazon" },
  { "image": "ambulance", "translation": "ambulancia" },
  { "image": "american-sign-language-interpreting", "translation": "interpretación de lenguaje de señas americano" },
  { "image": "anchor", "translation": "ancla" },
  { "image": "android", "translation": "android" },
  { "image": "angellist", "translation": "angellist" },
  { "image": "angle-double-down", "translation": "ángulo doble hacia abajo" },
  { "image": "angle-double-left", "translation": "ángulo doble hacia la izquierda" },
  { "image": "angle-double-right", "translation": "ángulo doble hacia la derecha" },
  { "image": "angle-double-up", "translation": "ángulo doble hacia arriba" },
  { "image": "angle-down", "translation": "ángulo hacia abajo" },
  { "image": "angle-left", "translation": "ángulo hacia la izquierda" },
  { "image": "angle-right", "translation": "ángulo hacia la derecha" },
  { "image": "angle-up", "translation": "ángulo hacia arriba" },
  { "image": "apple", "translation": "apple" },
  { "image": "archive", "translation": "archivo" },
  { "image": "area-chart", "translation": "gráfico de área" },
  { "image": "arrow-circle-down", "translation": "flecha en círculo hacia abajo" },
  { "image": "arrow-circle-left", "translation": "flecha en círculo hacia la izquierda" },
  { "image": "arrow-circle-o-down", "translation": "flecha en círculo-o hacia abajo" },
  { "image": "arrow-circle-o-left", "translation": "flecha en círculo-o hacia la izquierda" },
  { "image": "arrow-circle-o-right", "translation": "flecha en círculo-o hacia la derecha" },
  { "image": "arrow-circle-o-up", "translation": "flecha en círculo-o hacia arriba" },
  { "image": "arrow-circle-right", "translation": "flecha en círculo hacia la derecha" },
  { "image": "arrow-circle-up", "translation": "flecha en círculo hacia arriba" },
  { "image": "arrow-down", "translation": "flecha hacia abajo" },
  { "image": "arrow-left", "translation": "flecha hacia la izquierda" },
  { "image": "arrow-right", "translation": "flecha hacia la derecha" },
  { "image": "arrow-up", "translation": "flecha hacia arriba" },
  { "image": "arrows", "translation": "flechas" },
  { "image": "arrows-alt", "translation": "flechas alternativas" },
  { "image": "arrows-h", "translation": "flechas horizontales" },
  { "image": "arrows-v", "translation": "flechas verticales" },
  { "image": "asl-interpreting", "translation": "interpretación de lenguaje de señas" },
  { "image": "assistive-listening-systems", "translation": "sistemas de audición asistida" },
  { "image": "asterisk", "translation": "asterisco" },
  { "image": "at", "translation": "arroba" },
  { "image": "audio-description", "translation": "descripción de audio" },
  { "image": "automobile", "translation": "automóvil" },
  { "image": "backward", "translation": "hacia atrás" },
  { "image": "balance-scale", "translation": "balanza" },
  { "image": "ban", "translation": "prohibir" },
  { "image": "bandcamp", "translation": "bandcamp" },
  { "image": "bank", "translation": "banco" },
  { "image": "bar-chart", "translation": "gráfico de barras" },
  { "image": "bar-chart-o", "translation": "gráfico de barras-o" },
  { "image": "barcode", "translation": "código de barras" },
  { "image": "bars", "translation": "barras" },
  { "image": "bath", "translation": "baño" },
  { "image": "bathtub", "translation": "tina" },
  { "image": "battery-0", "translation": "batería 0" },
  { "image": "battery-1", "translation": "batería 1" },
  { "image": "battery-2", "translation": "batería 2" },
  { "image": "battery-3", "translation": "batería 3" },
  { "image": "battery-4", "translation": "batería 4" },
  { "image": "battery-empty", "translation": "batería vacía" },
  { "image": "battery-full", "translation": "batería llena" },
  { "image": "battery-half", "translation": "media batería" },
  { "image": "battery-quarter", "translation": "un cuarto de batería" },
  { "image": "battery-three-quarters", "translation": "tres cuartos de batería" },
  { "image": "bed", "translation": "cama" },
  { "image": "beer", "translation": "cerveza" },
  { "image": "behance", "translation": "behance" },
  { "image": "behance-square", "translation": "behance cuadrado" },
  { "image": "bell", "translation": "campana" },
  { "image": "bell-o", "translation": "campana-o" },
  { "image": "bell-slash", "translation": "campana tachada" },
  { "image": "bell-slash-o", "translation": "campana tachada-o" },
  { "image": "bicycle", "translation": "bicicleta" },
  { "image": "binoculars", "translation": "binoculares" },
  { "image": "birthday-cake", "translation": "pastel de cumpleaños" },
  { "image": "bitbucket", "translation": "bitbucket" },
  { "image": "bitbucket-square", "translation": "bitbucket cuadrado" },
  { "image": "bitcoin", "translation": "bitcoin" },
  { "image": "black-tie", "translation": "corbata negra" },
  { "image": "blind", "translation": "ciego" },
  { "image": "bluetooth", "translation": "bluetooth" },
  { "image": "bluetooth-b", "translation": "bluetooth-b" },
  { "image": "bold", "translation": "negrita" },
  { "image": "bolt", "translation": "rayo" },
  { "image": "bomb", "translation": "bomba" },
  { "image": "book", "translation": "libro" },
  { "image": "bookmark", "translation": "marcador" },
  { "image": "bookmark-o", "translation": "marcador-o" },
  { "image": "braille", "translation": "braille" },
  { "image": "briefcase", "translation": "maletín" },
  { "image": "btc", "translation": "btc" },
  { "image": "bug", "translation": "error" },
  { "image": "building", "translation": "edificio" },
  { "image": "building-o", "translation": "edificio-o" },
  { "image": "bullhorn", "translation": "altavoz" },
  { "image": "bullseye", "translation": "diana" },
  { "image": "bus", "translation": "autobús" },
  { "image": "buysellads", "translation": "buysellads" },
  { "image": "cab", "translation": "taxi" },
  { "image": "calculator", "translation": "calculadora" },
  { "image": "calendar", "translation": "calendario" },
  { "image": "calendar-check-o", "translation": "calendario con check-o" },
  { "image": "calendar-minus-o", "translation": "calendario con menos-o" },
  { "image": "calendar-o", "translation": "calendario-o" },
  { "image": "calendar-plus-o", "translation": "calendario con más-o" },
  { "image": "calendar-times-o", "translation": "calendario con x-o" },
  { "image": "camera", "translation": "cámara" },
  { "image": "camera-retro", "translation": "cámara retro" },
  { "image": "car", "translation": "coche" },
  { "image": "caret-down", "translation": "caret hacia abajo" },
  { "image": "caret-left", "translation": "caret hacia la izquierda" },
  { "image": "caret-right", "translation": "caret hacia la derecha" },
  { "image": "caret-square-o-down", "translation": "caret cuadrado-o hacia abajo" },
  { "image": "caret-square-o-left", "translation": "caret cuadrado-o hacia la izquierda" },
  { "image": "caret-square-o-right", "translation": "caret cuadrado-o hacia la derecha" },
  { "image": "caret-square-o-up", "translation": "caret cuadrado-o hacia arriba" },
  { "image": "caret-up", "translation": "caret hacia arriba" },
  { "image": "cart-arrow-down", "translation": "flecha del carrito hacia abajo" },
  { "image": "cart-plus", "translation": "carrito con más" },
  { "image": "cc", "translation": "cc" },
  { "image": "cc-amex", "translation": "cc amex" },
  { "image": "cc-diners-club", "translation": "cc diners club" },
  { "image": "cc-discover", "translation": "cc discover" },
  { "image": "cc-jcb", "translation": "cc jcb" },
  { "image": "cc-mastercard", "translation": "cc mastercard" },
  { "image": "cc-paypal", "translation": "cc paypal" },
  { "image": "cc-stripe", "translation": "cc stripe" },
  { "image": "cc-visa", "translation": "cc visa" },
  { "image": "certificate", "translation": "certificado" },
  { "image": "chain", "translation": "cadena" },
  { "image": "chain-broken", "translation": "cadena rota" },
  { "image": "check", "translation": "check" },
  { "image": "check-circle", "translation": "círculo con check" },
  { "image": "check-circle-o", "translation": "círculo con check-o" },
  { "image": "check-square", "translation": "cuadrado con check" },
  { "image": "check-square-o", "translation": "cuadrado con check-o" },
  { "image": "chevron-circle-down", "translation": "chevron en círculo hacia abajo" },
  { "image": "chevron-circle-left", "translation": "chevron en círculo hacia la izquierda" },
  { "image": "chevron-circle-right", "translation": "chevron en círculo hacia la derecha" },
  { "image": "chevron-circle-up", "translation": "chevron en círculo hacia arriba" },
  { "image": "chevron-down", "translation": "chevron hacia abajo" },
  { "image": "chevron-left", "translation": "chevron hacia la izquierda" },
  { "image": "chevron-right", "translation": "chevron hacia la derecha" },
  { "image": "chevron-up", "translation": "chevron hacia arriba" },
  { "image": "child", "translation": "niño" },
  { "image": "chrome", "translation": "chrome" },
  { "image": "circle", "translation": "círculo" },
  { "image": "circle-o", "translation": "círculo-o" },
  { "image": "circle-o-notch", "translation": "círculo-o con muesca" },
  { "image": "circle-thin", "translation": "círculo delgado" },
  { "image": "clipboard", "translation": "portapapeles" },
  { "image": "clock-o", "translation": "reloj-o" },
  { "image": "clone", "translation": "clonar" },
  { "image": "close", "translation": "cerrar" },
  { "image": "cloud", "translation": "nube" },
  { "image": "cloud-download", "translation": "descargar de la nube" },
  { "image": "cloud-upload", "translation": "subir a la nube" },
  { "image": "cny", "translation": "cny" },
  { "image": "code", "translation": "código" },
  { "image": "code-fork", "translation": "bifurcación de código" },
  { "image": "codepen", "translation": "codepen" },
  { "image": "codiepie", "translation": "codiepie" },
  { "image": "coffee", "translation": "café" },
  { "image": "cog", "translation": "engranaje" },
  { "image": "cogs", "translation": "engranajes" },
  { "image": "columns", "translation": "columnas" },
  { "image": "comment", "translation": "comentario" },
  { "image": "comment-o", "translation": "comentario-o" },
  { "image": "commenting", "translation": "comentando" },
  { "image": "commenting-o", "translation": "comentando-o" },
  { "image": "comments", "translation": "comentarios" },
  { "image": "comments-o", "translation": "comentarios-o" },
  { "image": "compass", "translation": "brújula" },
  { "image": "compress", "translation": "comprimir" },
  { "image": "connectdevelop", "translation": "connectdevelop" },
  { "image": "contao", "translation": "contao" },
  { "image": "copy", "translation": "copiar" },
  { "image": "copyright", "translation": "derechos de autor" },
  { "image": "creative-commons", "translation": "creative commons" },
  { "image": "credit-card", "translation": "tarjeta de crédito" },
  { "image": "credit-card-alt", "translation": "tarjeta de crédito alternativa" },
  { "image": "crop", "translation": "recortar" },
  { "image": "crosshairs", "translation": "punto de mira" },
  { "image": "css3", "translation": "css3" },
  { "image": "cube", "translation": "cubo" },
  { "image": "cubes", "translation": "cubos" },
  { "image": "cut", "translation": "cortar" },
  { "image": "cutlery", "translation": "cubiertos" },
  { "image": "dashboard", "translation": "tablero" },
  { "image": "dashcube", "translation": "dashcube" },
  { "image": "database", "translation": "base de datos" },
  { "image": "deaf", "translation": "sordo" },
  { "image": "deafness", "translation": "sordera" },
  { "image": "dedent", "translation": "eliminar sangría" },
  { "image": "delicious", "translation": "delicious" },
  { "image": "desktop", "translation": "escritorio" },
  { "image": "deviantart", "translation": "deviantart" },
  { "image": "diamond", "translation": "diamante" },
  { "image": "digg", "translation": "digg" },
  { "image": "dollar", "translation": "dólar" },
  { "image": "dot-circle-o", "translation": "círculo con punto-o" },
  { "image": "download", "translation": "descargar" },
  { "image": "dribbble", "translation": "dribbble" },
  { "image": "drivers-license", "translation": "licencia de conducir" },
  { "image": "drivers-license-o", "translation": "licencia de conducir-o" },
  { "image": "dropbox", "translation": "dropbox" },
  { "image": "drupal", "translation": "drupal" },
  { "image": "edge", "translation": "edge" },
  { "image": "edit", "translation": "editar" },
  { "image": "eercast", "translation": "eercast" },
  { "image": "eject", "translation": "expulsar" },
  { "image": "ellipsis-h", "translation": "elipsis-h" },
  { "image": "ellipsis-v", "translation": "elipsis-v" },
  { "image": "empire", "translation": "imperio" },
  { "image": "envelope", "translation": "sobre" },
  { "image": "envelope-o", "translation": "sobre-o" },
  { "image": "envelope-open", "translation": "sobre abierto" },
  { "image": "envelope-open-o", "translation": "sobre abierto-o" },
  { "image": "envelope-square", "translation": "sobre cuadrado" },
  { "image": "envira", "translation": "envira" },
  { "image": "eraser", "translation": "borrador" },
  { "image": "etsy", "translation": "etsy" },
  { "image": "eur", "translation": "eur" },
  { "image": "euro", "translation": "euro" },
  { "image": "exchange", "translation": "intercambio" },
  { "image": "exclamation", "translation": "exclamación" },
  { "image": "exclamation-circle", "translation": "círculo con exclamación" },
  { "image": "exclamation-triangle", "translation": "triángulo con exclamación" },
  { "image": "expand", "translation": "expandir" },
  { "image": "expeditedssl", "translation": "expeditedssl" },
  { "image": "external-link", "translation": "enlace externo" },
  { "image": "external-link-square", "translation": "enlace externo cuadrado" },
  { "image": "eye", "translation": "ojo" },
  { "image": "eye-slash", "translation": "ojo tachado" },
  { "image": "eyedropper", "translation": "cuentagotas" },
  { "image": "fa", "translation": "fa" },
  { "image": "facebook", "translation": "facebook" },
  { "image": "facebook-f", "translation": "facebook-f" },
  { "image": "facebook-official", "translation": "facebook oficial" },
  { "image": "facebook-square", "translation": "facebook cuadrado" },
  { "image": "fast-backward", "translation": "retroceso rápido" },
  { "image": "fast-forward", "translation": "avance rápido" },
  { "image": "fax", "translation": "fax" },
  { "image": "feed", "translation": "feed" },
  { "image": "female", "translation": "femenino" },
  { "image": "fighter-jet", "translation": "caza" },
  { "image": "file", "translation": "archivo" },
  { "image": "file-archive-o", "translation": "archivo comprimido-o" },
  { "image": "file-audio-o", "translation": "archivo de audio-o" },
  { "image": "file-code-o", "translation": "archivo de código-o" },
  { "image": "file-excel-o", "translation": "archivo de excel-o" },
  { "image": "file-image-o", "translation": "archivo de imagen-o" },
  { "image": "file-movie-o", "translation": "archivo de película-o" },
  { "image": "file-o", "translation": "archivo-o" },
  { "image": "file-pdf-o", "translation": "archivo pdf-o" },
  { "image": "file-photo-o", "translation": "archivo de foto-o" },
  { "image": "file-picture-o", "translation": "archivo de imagen-o" },
  { "image": "file-powerpoint-o", "translation": "archivo de powerpoint-o" },
  { "image": "file-sound-o", "translation": "archivo de sonido-o" },
  { "image": "file-text", "translation": "archivo de texto" },
  { "image": "file-text-o", "translation": "archivo de texto-o" },
  { "image": "file-video-o", "translation": "archivo de video-o" },
  { "image": "file-word-o", "translation": "archivo de word-o" },
  { "image": "file-zip-o", "translation": "archivo comprimido-o" },
  { "image": "files-o", "translation": "archivos-o" },
  { "image": "film", "translation": "película" },
  { "image": "filter", "translation": "filtro" },
  { "image": "fire", "translation": "fuego" },
  { "image": "fire-extinguisher", "translation": "extintor" },
  { "image": "firefox", "translation": "firefox" },
  { "image": "first-order", "translation": "first order" },
  { "image": "flag", "translation": "bandera" },
  { "image": "flag-checkered", "translation": "bandera a cuadros" },
  { "image": "flag-o", "translation": "bandera-o" },
  { "image": "flash", "translation": "flash" },
  { "image": "flask", "translation": "frasco" },
  { "image": "flickr", "translation": "flickr" },
  { "image": "floppy-o", "translation": "disquete-o" },
  { "image": "folder", "translation": "carpeta" },
  { "image": "folder-o", "translation": "carpeta-o" },
  { "image": "folder-open", "translation": "carpeta abierta" },
  { "image": "folder-open-o", "translation": "carpeta abierta-o" },
  { "image": "font", "translation": "fuente" },
  { "image": "font-awesome", "translation": "font awesome" },
  { "image": "fonticons", "translation": "fonticons" },
  { "image": "fort-awesome", "translation": "fort awesome" },
  { "image": "forumbee", "translation": "forumbee" },
  { "image": "forward", "translation": "avanzar" },
  { "image": "foursquare", "translation": "foursquare" },
  { "image": "free-code-camp", "translation": "free code camp" },
  { "image": "frown-o", "translation": "fruncir el ceño-o" },
  { "image": "futbol-o", "translation": "fútbol-o" },
  { "image": "gamepad", "translation": "gamepad" },
  { "image": "gavel", "translation": "mazo" },
  { "image": "gbp", "translation": "gbp" },
  { "image": "ge", "translation": "ge" },
  { "image": "gear", "translation": "engranaje" },
  { "image": "gears", "translation": "engranajes" },
  { "image": "genderless", "translation": "sin género" },
  { "image": "get-pocket", "translation": "get pocket" },
  { "image": "gg", "translation": "gg" },
  { "image": "gg-circle", "translation": "gg círculo" },
  { "image": "gift", "translation": "regalo" },
  { "image": "git", "translation": "git" },
  { "image": "git-square", "translation": "git cuadrado" },
  { "image": "github", "translation": "github" },
  { "image": "github-alt", "translation": "github alt" },
  { "image": "github-square", "translation": "github cuadrado" },
  { "image": "gitlab", "translation": "gitlab" },
  { "image": "gittip", "translation": "gittip" },
  { "image": "glass", "translation": "vaso" },
  { "image": "glide", "translation": "glide" },
  { "image": "glide-g", "translation": "glide-g" },
  { "image": "globe", "translation": "globo" },
  { "image": "google", "translation": "google" },
  { "image": "google-plus", "translation": "google plus" },
  { "image": "google-plus-circle", "translation": "google plus círculo" },
  { "image": "google-plus-official", "translation": "google plus oficial" },
  { "image": "google-plus-square", "translation": "google plus cuadrado" },
  { "image": "google-wallet", "translation": "google wallet" },
  { "image": "graduation-cap", "translation": "birrete" },
  { "image": "gratipay", "translation": "gratipay" },
  { "image": "grav", "translation": "grav" },
  { "image": "group", "translation": "grupo" },
  { "image": "h-square", "translation": "h cuadrado" },
  { "image": "hacker-news", "translation": "hacker news" },
  { "image": "hand-grab-o", "translation": "mano de agarre-o" },
  { "image": "hand-lizard-o", "translation": "mano de lagarto-o" },
  { "image": "hand-o-down", "translation": "mano-o hacia abajo" },
  { "image": "hand-o-left", "translation": "mano-o hacia la izquierda" },
  { "image": "hand-o-right", "translation": "mano-o hacia la derecha" },
  { "image": "hand-o-up", "translation": "mano-o hacia arriba" },
  { "image": "hand-paper-o", "translation": "mano de papel-o" },
  { "image": "hand-peace-o", "translation": "mano de paz-o" },
  { "image": "hand-pointer-o", "translation": "mano apuntando-o" },
  { "image": "hand-rock-o", "translation": "mano de roca-o" },
  { "image": "hand-scissors-o", "translation": "mano de tijeras-o" },
  { "image": "hand-spock-o", "translation": "mano de spock-o" },
  { "image": "hand-stop-o", "translation": "mano de stop-o" },
  { "image": "handshake-o", "translation": "apretón de manos-o" },
  { "image": "hard-of-hearing", "translation": "con problemas de audición" },
  { "image": "hashtag", "translation": "hashtag" },
  { "image": "hdd-o", "translation": "hdd-o" },
  { "image": "header", "translation": "cabecera" },
  { "image": "headphones", "translation": "auriculares" },
  { "image": "heart", "translation": "corazón" },
  { "image": "heart-o", "translation": "corazón-o" },
  { "image": "heartbeat", "translation": "latido del corazón" },
  { "image": "history", "translation": "historia" },
  { "image": "home", "translation": "inicio" },
  { "image": "hospital-o", "translation": "hospital-o" },
  { "image": "hotel", "translation": "hotel" },
  { "image": "hourglass", "translation": "reloj de arena" },
  { "image": "hourglass-1", "translation": "reloj de arena-1" },
  { "image": "hourglass-2", "translation": "reloj de arena-2" },
  { "image": "hourglass-3", "translation": "reloj de arena-3" },
  { "image": "hourglass-end", "translation": "reloj de arena terminado" },
  { "image": "hourglass-half", "translation": "reloj de arena a la mitad" },
  { "image": "hourglass-o", "translation": "reloj de arena-o" },
  { "image": "hourglass-start", "translation": "reloj de arena comenzando" },
  { "image": "houzz", "translation": "houzz" },
  { "image": "html5", "translation": "html5" },
  { "image": "i-cursor", "translation": "cursor i" },
  { "image": "id-badge", "translation": "insignia de identificación" },
  { "image": "id-card", "translation": "tarjeta de identificación" },
  { "image": "id-card-o", "translation": "tarjeta de identificación-o" },
  { "image": "ils", "translation": "ils" },
  { "image": "image", "translation": "imagen" },
  { "image": "imdb", "translation": "imdb" },
  { "image": "inbox", "translation": "bandeja de entrada" },
  { "image": "indent", "translation": "sangría" },
  { "image": "industry", "translation": "industria" },
  { "image": "info", "translation": "información" },
  { "image": "info-circle", "translation": "círculo de información" },
  { "image": "inr", "translation": "inr" },
  { "image": "instagram", "translation": "instagram" },
  { "image": "institution", "translation": "institución" },
  { "image": "internet-explorer", "translation": "internet explorer" },
  { "image": "intersex", "translation": "intersexual" },
  { "image": "ioxhost", "translation": "ioxhost" },
  { "image": "italic", "translation": "itálica" },
  { "image": "joomla", "translation": "joomla" },
  { "image": "jpy", "translation": "jpy" },
  { "image": "jsfiddle", "translation": "jsfiddle" },
  { "image": "key", "translation": "llave" },
  { "image": "keyboard-o", "translation": "teclado-o" },
  { "image": "krw", "translation": "krw" },
  { "image": "language", "translation": "idioma" },
  { "image": "laptop", "translation": "portátil" },
  { "image": "lastfm", "translation": "lastfm" },
  { "image": "lastfm-square", "translation": "lastfm cuadrado" },
  { "image": "leaf", "translation": "hoja" },
  { "image": "leanpub", "translation": "leanpub" },
  { "image": "legal", "translation": "legal" },
  { "image": "lemon-o", "translation": "limón-o" },
  { "image": "level-down", "translation": "nivel hacia abajo" },
  { "image": "level-up", "translation": "nivel hacia arriba" },
  { "image": "life-bouy", "translation": "flotador" },
  { "image": "life-buoy", "translation": "flotador" },
  { "image": "life-ring", "translation": "anillo salvavidas" },
  { "image": "life-saver", "translation": "salvavidas" },
  { "image": "lightbulb-o", "translation": "bombilla-o" },
  { "image": "line-chart", "translation": "gráfico de líneas" },
  { "image": "link", "translation": "enlace" },
  { "image": "linkedin", "translation": "linkedin" },
  { "image": "linkedin-square", "translation": "linkedin cuadrado" },
  { "image": "linode", "translation": "linode" },
  { "image": "linux", "translation": "linux" },
  { "image": "list", "translation": "lista" },
  { "image": "list-alt", "translation": "lista alternativa" },
  { "image": "list-ol", "translation": "lista ordenada" },
  { "image": "list-ul", "translation": "lista desordenada" },
  { "image": "location-arrow", "translation": "flecha de ubicación" },
  { "image": "lock", "translation": "bloquear" },
  { "image": "long-arrow-down", "translation": "flecha larga hacia abajo" },
  { "image": "long-arrow-left", "translation": "flecha larga hacia la izquierda" },
  { "image": "long-arrow-right", "translation": "flecha larga hacia la derecha" },
  { "image": "long-arrow-up", "translation": "flecha larga hacia arriba" },
  { "image": "low-vision", "translation": "visión baja" },
  { "image": "luggage", "translation": "equipaje" },
  { "image": "magic", "translation": "magia" },
  { "image": "magnet", "translation": "imán" },
  { "image": "mail-forward", "translation": "reenviar correo" },
  { "image": "mail-reply", "translation": "responder correo" },
  { "image": "mail-reply-all", "translation": "responder a todos los correos" },
  { "image": "male", "translation": "masculino" },
  { "image": "map", "translation": "mapa" },
  { "image": "map-marker", "translation": "marcador de mapa" },
  { "image": "map-o", "translation": "mapa-o" },
  { "image": "map-pin", "translation": "pin de mapa" },
  { "image": "map-signs", "translation": "señales de mapa" },
  { "image": "mars", "translation": "marte" },
  { "image": "mars-double", "translation": "marte doble" },
  { "image": "mars-stroke", "translation": "golpe de marte" },
  { "image": "mars-stroke-h", "translation": "golpe de marte-h" },
  { "image": "mars-stroke-v", "translation": "golpe de marte-v" },
  { "image": "maxcdn", "translation": "maxcdn" },
  { "image": "meanpath", "translation": "meanpath" },
  { "image": "medium", "translation": "medium" },
  { "image": "medkit", "translation": "kit médico" },
  { "image": "meetup", "translation": "meetup" },
  { "image": "meh-o", "translation": "meh-o" },
  { "image": "mercury", "translation": "mercurio" },
  { "image": "microchip", "translation": "microchip" },
  { "image": "microphone", "translation": "micrófono" },
  { "image": "microphone-slash", "translation": "micrófono silenciado" },
  { "image": "minus", "translation": "menos" },
  { "image": "minus-circle", "translation": "círculo con menos" },
  { "image": "minus-square", "translation": "cuadrado con menos" },
  { "image": "minus-square-o", "translation": "cuadrado con menos-o" },
  { "image": "mix", "translation": "mezcla" },
  { "image": "mixcloud", "translation": "mixcloud" },
  { "image": "mobile", "translation": "móvil" },
  { "image": "mobile-phone", "translation": "teléfono móvil" },
  { "image": "modx", "translation": "modx" },
  { "image": "money", "translation": "dinero" },
  { "image": "moon-o", "translation": "luna-o" },
  { "image": "mortar-board", "translation": "birrete" },
  { "image": "motorcycle", "translation": "motocicleta" },
  { "image": "mouse-pointer", "translation": "puntero del ratón" },
  { "image": "music", "translation": "música" },
  { "image": "navicon", "translation": "navicon" },
  { "image": "neuter", "translation": "neutro" },
  { "image": "newspaper-o", "translation": "periódico-o" },
  { "image": "object-group", "translation": "grupo de objetos" },
  { "image": "object-ungroup", "translation": "desagrupar objetos" },
  { "image": "odnoklassniki", "translation": "odnoklassniki" },
  { "image": "odnoklassniki-square", "translation": "odnoklassniki cuadrado" },
  { "image": "opencart", "translation": "opencart" },
  { "image": "openid", "translation": "openid" },
  { "image": "opera", "translation": "opera" },
  { "image": "optin-monster", "translation": "optin monster" },
  { "image": "outdent", "translation": "sangría negativa" },
  { "image": "pagelines", "translation": "pagelines" },
  { "image": "paint-brush", "translation": "brocha" },
  { "image": "paper-plane", "translation": "avión de papel" },
  { "image": "paper-plane-o", "translation": "avión de papel-o" },
  { "image": "paperclip", "translation": "clip" },
  { "image": "paragraph", "translation": "párrafo" },
  { "image": "paste", "translation": "pegar" },
  { "image": "pause", "translation": "pausar" },
  { "image": "pause-circle", "translation": "círculo de pausa" },
  { "image": "pause-circle-o", "translation": "círculo de pausa-o" },
  { "image": "paw", "translation": "pata" },
  { "image": "paypal", "translation": "paypal" },
  { "image": "pencil", "translation": "lápiz" },
  { "image": "pencil-square", "translation": "cuadrado de lápiz" },
  { "image": "pencil-square-o", "translation": "cuadrado de lápiz-o" },
  { "image": "percent", "translation": "porcentaje" },
  { "image": "phone", "translation": "teléfono" },
  { "image": "phone-square", "translation": "teléfono cuadrado" },
  { "image": "photo", "translation": "foto" },
  { "image": "picture-o", "translation": "imagen-o" },
  { "image": "pie-chart", "translation": "gráfico circular" },
  { "image": "pied-piper", "translation": "pied piper" },
  { "image": "pied-piper-alt", "translation": "pied piper alt" },
  { "image": "pied-piper-pp", "translation": "pied piper pp" },
  { "image": "pinterest", "translation": "pinterest" },
  { "image": "pinterest-p", "translation": "pinterest-p" },
  { "image": "pinterest-square", "translation": "pinterest cuadrado" },
  { "image": "plane", "translation": "avión" },
  { "image": "play", "translation": "reproducir" },
  { "image": "play-circle", "translation": "círculo de reproducción" },
  { "image": "play-circle-o", "translation": "círculo de reproducción-o" },
  { "image": "plug", "translation": "enchufe" },
  { "image": "plus", "translation": "más" },
  { "image": "plus-circle", "translation": "círculo con más" },
  { "image": "plus-square", "translation": "cuadrado con más" },
  { "image": "plus-square-o", "translation": "cuadrado con más-o" },
  { "image": "podcast", "translation": "podcast" },
  { "image": "power-off", "translation": "apagar" },
  { "image": "print", "translation": "imprimir" },
  { "image": "product-hunt", "translation": "product hunt" },
  { "image": "puzzle-piece", "translation": "pieza de rompecabezas" },
  { "image": "qq", "translation": "qq" },
  { "image": "qrcode", "translation": "código qr" },
  { "image": "question", "translation": "pregunta" },
  { "image": "question-circle", "translation": "círculo de pregunta" },
  { "image": "question-circle-o", "translation": "círculo de pregunta-o" },
  { "image": "quora", "translation": "quora" },
  { "image": "quote-left", "translation": "comillas izquierda" },
  { "image": "quote-right", "translation": "comillas derecha" },
  { "image": "ra", "translation": "ra" },
  { "image": "random", "translation": "aleatorio" },
  { "image": "ravelry", "translation": "ravelry" },
  { "image": "rebel", "translation": "rebelde" },
  { "image": "recycle", "translation": "reciclar" },
  { "image": "reddit", "translation": "reddit" },
  { "image": "reddit-alien", "translation": "alienígena de reddit" },
  { "image": "reddit-square", "translation": "reddit cuadrado" },
  { "image": "refresh", "translation": "refrescar" },
  { "image": "registered", "translation": "registrado" },
  { "image": "remove", "translation": "eliminar" },
  { "image": "renren", "translation": "renren" },
  { "image": "reorder", "translation": "reordenar" },
  { "image": "repeat", "translation": "repetir" },
  { "image": "reply", "translation": "responder" },
  { "image": "reply-all", "translation": "responder a todos" },
  { "image": "retweet", "translation": "retweet" },
  { "image": "rmb", "translation": "rmb" },
  { "image": "road", "translation": "carretera" },
  { "image": "rocket", "translation": "cohete" },
  { "image": "rotate-left", "translation": "girar a la izquierda" },
  { "image": "rotate-right", "translation": "girar a la derecha" },
  { "image": "rouble", "translation": "rublo" },
  { "image": "rss", "translation": "rss" },
  { "image": "rss-square", "translation": "rss cuadrado" },
  { "image": "rub", "translation": "frotar" },
  { "image": "ruble", "translation": "rublo" },
  { "image": "rupee", "translation": "rupia" },
  { "image": "safari", "translation": "safari" },
  { "image": "save", "translation": "guardar" },
  { "image": "scissors", "translation": "tijeras" },
  { "image": "scribd", "translation": "scribd" },
  { "image": "search", "translation": "buscar" },
  { "image": "search-minus", "translation": "buscar con menos" },
  { "image": "search-plus", "translation": "buscar con más" },
  { "image": "sellsy", "translation": "sellsy" },
  { "image": "send", "translation": "enviar" },
  { "image": "send-o", "translation": "enviar-o" },
  { "image": "server", "translation": "servidor" },
  { "image": "share", "translation": "compartir" },
  { "image": "share-alt", "translation": "compartir-alt" },
  { "image": "share-alt-square", "translation": "compartir-alt cuadrado" },
  { "image": "share-square", "translation": "compartir cuadrado" },
  { "image": "share-square-o", "translation": "compartir cuadrado-o" },
  { "image": "shekel", "translation": "shekel" },
  { "image": "sheqel", "translation": "shekel" },
  { "image": "shield", "translation": "escudo" },
  { "image": "ship", "translation": "barco" },
  { "image": "shirtsinbulk", "translation": "shirtsinbulk" },
  { "image": "shopping-bag", "translation": "bolsa de compras" },
  { "image": "shopping-basket", "translation": "cesta de compras" },
  { "image": "shopping-cart", "translation": "carrito de compras" },
  { "image": "shower", "translation": "ducha" },
  { "image": "sign-in", "translation": "iniciar sesión" },
  { "image": "sign-language", "translation": "lenguaje de señas" },
  { "image": "sign-out", "translation": "cerrar sesión" },
  { "image": "signal", "translation": "señal" },
  { "image": "signing", "translation": "firmar" },
  { "image": "simplybuilt", "translation": "simplybuilt" },
  { "image": "sitemap", "translation": "mapa del sitio" },
  { "image": "skyatlas", "translation": "skyatlas" },
  { "image": "skype", "translation": "skype" },
  { "image": "slack", "translation": "slack" },
  { "image": "sliders", "translation": "deslizadores" },
  { "image": "slideshare", "translation": "slideshare" },
  { "image": "smile-o", "translation": "sonrisa-o" },
  { "image": "snapchat", "translation": "snapchat" },
  { "image": "snapchat-ghost", "translation": "fantasma de snapchat" },
  { "image": "snapchat-square", "translation": "snapchat cuadrado" },
  { "image": "snowflake-o", "translation": "copo de nieve-o" },
  { "image": "soccer-ball-o", "translation": "balón de fútbol-o" },
  { "image": "sort", "translation": "ordenar" },
  { "image": "sort-alpha-asc", "translation": "ordenar alfabéticamente ascendente" },
  { "image": "sort-alpha-desc", "translation": "ordenar alfabéticamente descendente" },
  { "image": "sort-amount-asc", "translation": "ordenar por cantidad ascendente" },
  { "image": "sort-amount-desc", "translation": "ordenar por cantidad descendente" },
  { "image": "sort-asc", "translation": "ordenar ascendente" },
  { "image": "sort-desc", "translation": "ordenar descendente" },
  { "image": "sort-down", "translation": "ordenar hacia abajo" },
  { "image": "sort-numeric-asc", "translation": "ordenar numéricamente ascendente" },
  { "image": "sort-numeric-desc", "translation": "ordenar numéricamente descendente" },
  { "image": "sort-up", "translation": "ordenar hacia arriba" },
  { "image": "soundcloud", "translation": "soundcloud" },
  { "image": "space-shuttle", "translation": "transbordador espacial" },
  { "image": "spinner", "translation": "spinner" },
  { "image": "spoon", "translation": "cuchara" },
  { "image": "spotify", "translation": "spotify" },
  { "image": "square", "translation": "cuadrado" },
  { "image": "square-o", "translation": "cuadrado-o" },
  { "image": "stack-exchange", "translation": "stack exchange" },
  { "image": "stack-overflow", "translation": "stack overflow" },
  { "image": "star", "translation": "estrella" },
  { "image": "star-half", "translation": "media estrella" },
  { "image": "star-half-empty", "translation": "media estrella vacía" },
  { "image": "star-half-full", "translation": "media estrella llena" },
  { "image": "star-half-o", "translation": "media estrella-o" },
  { "image": "star-o", "translation": "estrella-o" },
  { "image": "steam", "translation": "steam" },
  { "image": "steam-square", "translation": "steam cuadrado" },
  { "image": "step-backward", "translation": "retroceder" },
  { "image": "step-forward", "translation": "avanzar" },
  { "image": "stethoscope", "translation": "estetoscopio" },
  { "image": "sticky-note", "translation": "nota adhesiva" },
  { "image": "sticky-note-o", "translation": "nota adhesiva-o" },
  { "image": "stop", "translation": "detener" },
  { "image": "stop-circle", "translation": "círculo de detención" },
  { "image": "stop-circle-o", "translation": "círculo de detención-o" },
  { "image": "street-view", "translation": "vista de calle" },
  { "image": "strikethrough", "translation": "tachado" },
  { "image": "stumbleupon", "translation": "stumbleupon" },
  { "image": "stumbleupon-circle", "translation": "stumbleupon círculo" },
  { "image": "subscript", "translation": "subíndice" },
  { "image": "subway", "translation": "subterráneo" },
  { "image": "suitcase", "translation": "maleta" },
  { "image": "sun-o", "translation": "sol-o" },
  { "image": "superpowers", "translation": "superpoderes" },
  { "image": "superscript", "translation": "superíndice" },
  { "image": "support", "translation": "soporte" },
  { "image": "table", "translation": "tabla" },
  { "image": "tablet", "translation": "tableta" },
  { "image": "tachometer", "translation": "tacómetro" },
  { "image": "tag", "translation": "etiqueta" },
  { "image": "tags", "translation": "etiquetas" },
  { "image": "tasks", "translation": "tareas" },
  { "image": "taxi", "translation": "taxi" },
  { "image": "telegram", "translation": "telegram" },
  { "image": "television", "translation": "televisión" },
  { "image": "tencent-weibo", "translation": "tencent weibo" },
  { "image": "terminal", "translation": "terminal" },
  { "image": "text-height", "translation": "altura del texto" },
  { "image": "text-width", "translation": "ancho del texto" },
  { "image": "th", "translation": "th" },
  { "image": "th-large", "translation": "th grande" },
  { "image": "th-list", "translation": "th lista" },
  { "image": "themeisle", "translation": "themeisle" },
  { "image": "thermometer", "translation": "termómetro" },
  { "image": "thermometer-0", "translation": "termómetro 0" },
  { "image": "thermometer-1", "translation": "termómetro 1" },
  { "image": "thermometer-2", "translation": "termómetro 2" },
  { "image": "thermometer-3", "translation": "termómetro 3" },
  { "image": "thermometer-4", "translation": "termómetro 4" },
  { "image": "thermometer-empty", "translation": "termómetro vacío" },
  { "image": "thermometer-full", "translation": "termómetro lleno" },
  { "image": "thermometer-half", "translation": "termómetro medio" },
  { "image": "thermometer-quarter", "translation": "termómetro cuarto" },
  { "image": "thermometer-three-quarters", "translation": "termómetro tres cuartos" },
  { "image": "thumb-tack", "translation": "chincheta" },
  { "image": "thumb-tack-alt", "translation": "chincheta-alt" },
  { "image": "thumbs-down", "translation": "pulgares hacia abajo" },
  { "image": "thumbs-o-down", "translation": "pulgares hacia abajo-o" },
  { "image": "thumbs-o-up", "translation": "pulgares hacia arriba-o" },
  { "image": "thumbs-up", "translation": "pulgares hacia arriba" },
  { "image": "ticket", "translation": "boleto" },
  { "image": "times", "translation": "veces" },
  { "image": "times-circle", "translation": "círculo de veces" },
  { "image": "times-circle-o", "translation": "círculo de veces-o" },
  { "image": "tint", "translation": "tinta" },
  { "image": "toggle-down", "translation": "alternar hacia abajo" },
  { "image": "toggle-left", "translation": "alternar hacia la izquierda" },
  { "image": "toggle-off", "translation": "alternar desactivado" },
  { "image": "toggle-on", "translation": "alternar activado" },
  { "image": "toggle-right", "translation": "alternar hacia la derecha" },
  { "image": "toggle-up", "translation": "alternar hacia arriba" },
  { "image": "trademark", "translation": "marca registrada" },
  { "image": "train", "translation": "tren" },
  { "image": "transgender", "translation": "transgénero" },
  { "image": "transgender-alt", "translation": "transgénero-alt" },
  { "image": "trash", "translation": "basura" },
  { "image": "trash-o", "translation": "basura-o" },
  { "image": "tree", "translation": "árbol" },
  { "image": "trello", "translation": "trello" },
  { "image": "tripadvisor", "translation": "tripadvisor" },
  { "image": "trophy", "translation": "trofeo" },
  { "image": "truck", "translation": "camión" },
  { "image": "try", "translation": "intentar" },
  { "image": "tty", "translation": "tty" },
  { "image": "tumblr", "translation": "tumblr" },
  { "image": "tumblr-square", "translation": "tumblr cuadrado" },
  { "image": "turkish-lira", "translation": "lira turca" },
  { "image": "tv", "translation": "tv" },
  { "image": "twitch", "translation": "twitch" },
  { "image": "twitter", "translation": "twitter" },
  { "image": "twitter-square", "translation": "twitter cuadrado" },
  { "image": "umbrella", "translation": "paraguas" },
  { "image": "underline", "translation": "subrayar" },
  { "image": "undo", "translation": "deshacer" },
  { "image": "universal-access", "translation": "acceso universal" },
  { "image": "university", "translation": "universidad" },
  { "image": "unlink", "translation": "desvincular" },
  { "image": "unlock", "translation": "desbloquear" },
  { "image": "unlock-alt", "translation": "desbloquear-alt" },
  { "image": "unsorted", "translation": "no ordenado" },
  { "image": "upload", "translation": "cargar" },
  { "image": "usb", "translation": "usb" },
  { "image": "usd", "translation": "usd" },
  { "image": "user", "translation": "usuario" },
  { "image": "user-circle", "translation": "círculo de usuario" },
  { "image": "user-circle-o", "translation": "círculo de usuario-o" },
  { "image": "user-md", "translation": "usuario md" },
  { "image": "user-o", "translation": "usuario-o" },
  { "image": "user-plus", "translation": "usuario más" },
  { "image": "user-secret", "translation": "usuario secreto" },
  { "image": "user-times", "translation": "usuario veces" },
  { "image": "users", "translation": "usuarios" },
  { "image": "vcard", "translation": "vcard" },
  { "image": "venus", "translation": "venus" },
  { "image": "venus-double", "translation": "venus doble" },
  { "image": "venus-mars", "translation": "venus marte" },
  { "image": "viacoin", "translation": "viacoin" },
  { "image": "viadeo", "translation": "viadeo" },
  { "image": "viadeo-square", "translation": "viadeo cuadrado" },
  { "image": "video-camera", "translation": "cámara de video" },
  { "image": "vimeo", "translation": "vimeo" },
  { "image": "vimeo-square", "translation": "vimeo cuadrado" },
  { "image": "vine", "translation": "vine" },
  { "image": "vk", "translation": "vk" },
  { "image": "volume-control-phone", "translation": "teléfono con control de volumen" },
  { "image": "volume-down", "translation": "bajar volumen" },
  { "image": "volume-off", "translation": "silenciar" },
  { "image": "volume-up", "translation": "subir volumen" },
  { "image": "warning", "translation": "advertencia" },
  { "image": "wechat", "translation": "wechat" },
  { "image": "weibo", "translation": "weibo" },
  { "image": "weixin", "translation": "weixin" },
  { "image": "whatsapp", "translation": "whatsapp" },
  { "image": "wheelchair", "translation": "silla de ruedas" },
  { "image": "wheelchair-alt", "translation": "silla de ruedas-alt" },
  { "image": "wifi", "translation": "wifi" },
  { "image": "wikipedia-w", "translation": "wikipedia-w" },
  { "image": "window-close", "translation": "cerrar ventana" },
  { "image": "window-close-o", "translation": "cerrar ventana-o" },
  { "image": "window-maximize", "translation": "maximizar ventana" },
  { "image": "window-minimize", "translation": "minimizar ventana" },
  { "image": "window-restore", "translation": "restaurar ventana" },
  { "image": "windows", "translation": "windows" },
  { "image": "won", "translation": "ganado" },
  { "image": "wordpress", "translation": "wordpress" },
  { "image": "wpbeginner", "translation": "wpbeginner" },
  { "image": "wpexplorer", "translation": "wpexplorer" },
  { "image": "wpforms", "translation": "wpforms" },
  { "image": "wrench", "translation": "llave inglesa" },
  { "image": "xing", "translation": "xing" },
  { "image": "xing-square", "translation": "xing cuadrado" },
  { "image": "y-combinator", "translation": "y combinator" },
  { "image": "yahoo", "translation": "yahoo" },
  { "image": "yelp", "translation": "yelp" },
  { "image": "yen", "translation": "yen" },
  { "image": "yoast", "translation": "yoast" },
  { "image": "youtube", "translation": "youtube" },
  { "image": "youtube-play", "translation": "reproducir youtube" },
  { "image": "youtube-square", "translation": "youtube cuadrado" }
]

